
storage: /tmp/mirror

repositories:
  - path: mailru/shadowplay
    release_filter: AllowAll
    asset_filter: AllowAll

  - path: nodejs/node
    release_filter:
      DateRange:
        min: '2022-06-01T00:00:00Z'
        max: '2022-06-20T00:00:00Z'
    asset_filter:
      FileRegex:
        pattern: '[.]tar[.]gz$'

  - path: crev-dev/cargo-crev
    release_filter:
      FixedList:
        - v0.23.2
        - v0.22.2
    asset_filter:
      FileRegex:
        pattern: '[.]zip$'

  - path: sharkdp/bat
    release_filter:
      DateWindow:
        min_from_now: 1 year
        max_from_now: 2 weeks
    asset_filter:
      FileRegex:
        pattern: '_amd64[.]deb$'
  - path: golang/go
    release_filter:
      Regex:
        pattern: ^tag_go1[.]\d+([.]\d+)?$
    asset_filter:
      FileRegex:
        pattern: 'tar[.]gz$'
    include_tags: true
